name: GitHub CI
on: push

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: wix
        run: echo choco install wixtoolset

      - uses: actions/checkout@v1

      - name: Build
        shell: pwsh
        run: |
          $msbuildPath = Split-Path (& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\Current\Bin\amd64\MSBuild.exe | Select-Object -First 1) -Parent
          $env:PATH = $msbuildPath + ';' + $env:PATH
          msbuild -v:m -restore -t:Build -p:Configuration=Release MissionPlanner.sln

      - name: Cleanup
        shell: pwsh
        run: |
          cd bin\Release\net461
          gci plugins | ForEach-Object {                 if (Test-Path $_.Name -PathType Leaf)                {                    Write-Host "Remove" $_.FullName   ;                 Remove-Item $_.FullName                            } else {                    Write-Host $_.Name                }            }
          
      - uses: actions/upload-artifact@v1
        with:
          name: MissionPlannerBeta
          path: bin\Release\net461
      - name: msi
        run: |
          pwd
          cd msi
          ./wix.exe ..\bin\release\net461\
          &"${Env:wix}\bin\candle" installer.wxs -ext WiXNetFxExtension -ext WixDifxAppExtension -ext WixUIExtension.dll -ext WixUtilExtension -ext WixIisExtension 
          &"${Env:wix}\bin\light" installer.wixobj "${Env:wix}\bin\difxapp_x86.wixlib" -sval -o MissionPlanner-latest.msi -ext WiXNetFxExtension -ext WixDifxAppExtension -ext WixUIExtension.dll -ext WixUtilExtension -ext WixIisExtension 
      - uses: actions/upload-artifact@v1
        with:
          name: MissionPlannerBetaMSI
          path: msi\MissionPlanner-latest.msi
